name: production | 🚀 Deploy website on push
on:
  push:
    branches: [master]
  pull_request:
    types: [closed]
    branches: [master]
jobs:
  web-deploy:
    name: 🎉 Deploy to production
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.PROD_FTP_SERVER }}
        username: ${{ secrets.PROD_FTP_USERNAME }}
        password: ${{ secrets.PROD_FTP_PASSWORD }}
        dry-run: true
        server-dir: public_html/wp-content/themes/teachdigital/
        exclude: .git*
          - .git*/**
          -  **/.git*/**
          - node_modules/**
          - node_modules/**/*
          - .eslintrc.js
          - .gitignore
          - .eslintignore
          - .stylelintrc.json
          - gulpfile.js
          - package.json
          - package-lock.json
          - src/scss/*
          - src/scss/**/*
          - src/js/*
          - src/js/**/*